main: ml.pkom.jsonconfig.JsonConfig
name: JsonConfig
description: "This plugin is JsonConfig."
version: "1.0.0"
author: "Pitan"
website: "http://pkom.ml/?Minecraft/Spigot/%E8%87%AA%E4%BD%9C%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3"
commands:
  helloworld:
    description: "Message 'Hello World!' to player"
    aliases: [hw, hello]
    usage: "/helloworld"